- project:
    experimental:
      jobs:
        - mcom02-buildroot-build:
            vars:
              build_sdk: true

    check:
      jobs:
        - mcom02-buildroot-build:
            irrelevant-files:
              - ^fragments/linux54.fragment
        - mcom02-linux54-buildroot-build
        - pre-commit
