- project:
    check:
      jobs:
        - mcom02-buildroot-build:
            irrelevant-files:
              - ^fragments/linux54.fragment
        - mcom02-linux54-buildroot-build
        - pre-commit
