#!/bin/sh

if [ "$1" == "start" ]
then
	ifconfig wlan0 &> /dev/null
	rc=$?
	if [ -e /sys/bus/sdio/drivers/brcmfmac_sdio/mmc1:0001:2 -a $rc != 0 ]
	then
		echo '3800d000.sdhci1' > /sys/bus/platform/drivers/sdhci-arasan/unbind
		echo '3800d000.sdhci1' > /sys/bus/platform/drivers/sdhci-arasan/bind
	fi
fi
