#!/bin/sh -e

if [ ${IFACE:0:6} != "lowpan" ]; then
	exit 0
fi

WPAN=${IFACE:2}

if [ -n "$IF_PAN_ID" -o -n "$IF_PAN_ADDR" -o -n "$IF_PAN_CHANNEL" ]; then
	iz set $WPAN "$IF_PAN_ID" "$IF_PAN_ADDR" "$IF_PAN_CHANNEL"
fi

ip link set $WPAN up
ip link add link $WPAN name $IFACE type lowpan
ip link set $IFACE up
